### PR TITLE
docs(sharec): README misspell fix

### PR DESCRIPTION
**Pull request by albertmolodec**
I think there's been a little mistake. I tried to fix it:

> Add `posintall` and `uninstall` scripts to root package.json file:

↓ 

> Add **`postinstall`** and **`preuninstall`** scripts to root package.json file:

### CODE REVIEW

**Comment by lamartire** [comment]
Hey, @albertmolodec! Thank you for the first PR on this project! 🙌 
Please, can you correct commit message with [https://www.conventionalcommits.org/en/](https://www.conventionalcommits.org/en/)? This is very important.

**Comment by lamartire** [comment]
`docs(sharec): README misspell fix` would be nice.

**Comment by albertmolodec** [comment]
Hey, @lamartire!
I was having trouble with that. Thank you for your help :)

**Comment by albertmolodec** [comment]
One second, I'm thinking about how to change the name of the commit :D

**Comment by lamartire** [comment]
@albertmolodec, no, I mean commit message. You can edit it with `git rebase` command or with GUI client.

**Comment by lamartire** [comment]
@albertmolodec you can do it with `git rebase` command or with GUI client.
The another way – use `git reset --soft` to the last commit, commit changes with correct message and `push -f` to your fork.

**Comment by albertmolodec** [comment]
Done ✓

**Comment by lamartire** [comment]
@albertmolodec nice job, mate :)

**Pull request merged**
